language: cpp

os:
  - linux
  - osx

compiler:
    - gcc
    - clang

addons:
  apt:
    packages:
    - libboost-all-dev

script:
  - mkdir build_gcc && cd build_gcc && cmake .. && cmake --build . --target install && cd ..
