image: Visual Studio 2017
clone_folder: c:\projects\peoplebox
cache: C:\Tools\vcpkg\installed\

environment:
    WORKSPACE: C:\projects
    matrix:
    - platform: Win64
      COMPILER: vs
      configuration: Release
      VCPKG_ROOT: C:\Tools\vcpkg
      VCPKG_DEFAULT_TRIPLET: x64-windows

install:
  - cinst cmake ninja
  - SET "PATH=C:\Program Files\CMake\bin;%PATH%"
  - call "C:\Program Files (x86)\Microsoft Visual Studio\2017\Community\VC\Auxiliary\Build\vcvarsall.bat" x64
  - git submodule -q update --init --recursive
  - cd %WORKSPACE%\
  - cd %VCPKG_ROOT%
  - git pull
  - .\bootstrap-vcpkg.bat
  - echo set(VCPKG_BUILD_TYPE release) >> triplets\%VCPKG_DEFAULT_TRIPLET%.cmake
  - vcpkg install boost --recurse
  - cd %WORKSPACE%\mapsort\
  - mkdir build_release && cd build_release
  - if [%configuration%]==[Release] cmake -G "Visual Studio 15 2017" -T "host=x64" -A "x64" "-DCMAKE_TOOLCHAIN_FILE=%VCPKG_ROOT%\scripts\buildsystems\vcpkg.cmake" "-DVCPKG_TARGET_TRIPLET=%VCPKG_DEFAULT_TRIPLET%" -DCMAKE_BUILD_TYPE="Release" ..
  - cd ..

build_script:
  - if [%configuration%]==[Release] cd build_release && cmake --build . --config Release --parallel 8 --target install && cd ..

artifacts:
  - path: '*.exe'
